### ISSUE TITLE
Consider using loops instead of map/forEach

### ISSUE THREAD

**Issue by skosch** [reactabular/table-resolver#1]
I just profiled how long it takes to load my page (the main component of which is a table of a few hundred rows), and around 10% go to resolve.js. It amounts to 0.2–0.3 seconds, nothing catastrophic, but maybe you're willing to consider using naked loops here instead?

**Comment by bebraw** [comment]
Sure. If you PR, set up a little benchmark against the old code first so you have something to measure against when writing an improved version.

**Comment by skosch** [comment]
Glad you asked for a benchmark, because the difference is in the millisecond range – definitely not worth the uglier code. I'm guessing it really is the `get` calls that take up the most time? Anyway, 'twas worth a shot ...

**Comment by bebraw** [comment]
I wonder if it would be possible to memoize those calls. Worth a go.

**Comment by skosch** [comment]
Well I'd certainly love to memoize the creating of the actual resolver method each time:
```javascript
method({
        rowIndex,
        column
      })
```
Does anyone actually need the rowIndex there? Because if it's just by column, then there aren't that many, and we could create those ahead of time.

I'm not sure how we would memoize `get`, though. Lodash's `get` implementation breaks the path strings into arrays and it already caches those (up to 500 of them); beyond that it's mostly looping through them that takes time. Based on [this SO answer](http://stackoverflow.com/a/41532415/629578), it might be slightly faster to let users provide their getter directly, e.g. `a => (a["firstKey"] || {})["secondKey"]`, but that would have to be at their own risk.

**Comment by bebraw** [comment]
Ah, *that* `get`. I'm not sure of the right way here. I would say it depends also on your data. If it's not that nested, it would be likely possible to replace with a cheaper alternative and we can definitely allow that.

I can accept a PR for a custom getter as that might be a good idea anyway.

**Comment by skosch** [comment]
Cool. To my first question though: who needs the `rowIndex`?

**Comment by bebraw** [comment]
@skosch I don't remember anymore. You would have to dig some of the surrounding code to understand the reasoning for that. In the best case we can just drop it without breaking anything.

**Comment by skosch** [comment]
Alright, I'll give that a shot.

**Comment by skosch** [comment]
Ah, okay, so it's `resolve.index` that uses it. How about we get rid of that method altogether and we just provide `_.index` always, so we can memoize the method creation away?

**Comment by bebraw** [comment]
@skosch I recall `resolve.index` is needed for virtualization. But if you can rework the setup so `resolve.index` isn't needed anymore, that's even better.
