### ISSUE TITLE
Why Lodash is a peer dependency

### ISSUE THREAD

**Issue by sapegin** [reactabular/table-resolver#5]
I think it should be a normal dependency. I can send a PR for that.

**Comment by bebraw** [comment]
I left it as a peer dependency as it's the same as for the entire family of Reactabular packages. Here I simply state that it should work with Lodash of the given range. Why a normal dependency instead?

**Comment by sapegin** [comment]
Because it’s a dependency of a library, not of a consumer app like React. Users should not care that your library needs Lodash but their app should use a compatible version of React. That’s how a see the difference.

**Comment by bebraw** [comment]
Ok, feel free to PR.
